# Generated by Django 4.2.17 on 2025-01-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
